# Generated by Django 4.2 on 2023-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
